#TOPDIR = $(CURDIR)
TOPDIR = .
SITE ?= {{ site }}

guests ?= rhua cds1 cds2

#miniascape_OPTIONS = -t $(TOPDIR)/templates -C '/etc/miniascape.d/rhui/
miniascape_OPTIONS = -t $(TOPDIR)/templates


all: build

build:
	miniascape b $(miniascape_OPTIONS) -C $(TOPDIR)/$(SITE) -w $(TOPDIR)/out

setup:
	for d in $(wildcard $(TOPDIR)/out/guests.d/*); do test -d $$d && make -C $$d setup || :; done 

#for d in $(wildcard $(TOPDIR)/out/guests.d/*); do test -d $$d && make -C $$d/ setup; done

world:
	for vm in $(guests); do bash -x out/guests.d/$$vm/vmbuild.sh &; done

.PHONY: build setup world
