#TOPDIR = $(CURDIR)
TOPDIR = .
SITE ?= {{ site }}

guests ?= rhua cds1 cds2
miniascape_OPTIONS = -t $(TOPDIR)/templates


all: build


build:
	miniascape c -f -c '$(TOPDIR)/$(SITE)/*.yml' -w $(TOPDIR)/out $(miniascape_OPTIONS)

#for d in $(wildcard $(TOPDIR)/out/guests.d/*); do test -d $$d && make -C $$d/ setup; done

world:
	for vm in $(guests); do bash -x out/guests.d/$$vm/vmbuild.sh &; done

.PHONY: configure compile world
