# Makefile to define custom variables, rules and targets.
# Author: Satoru SATOH <ssato/redhat.com>
# License: MIT
#
ADMIN_NAME ?= admin
KATELLO_INSTALLER_OPTIONS ?= --foreman-admin-username=$(ADMIN_NAME)


KATELLO_INSTALLER_OPTIONS += \
--katello-proxy-url='http://proxy.example.com' \
--katello-proxy-port=1234 \
 \

PROXY_URL ?= http://proxy.example.com:1234
CURL_PROXY_OPT ?= --proxy $(PROXY_URL)
TWEAK_SELINUX_POLICY ?= semanage port -at foreman_proxy_port_t -p tcp 1234

# vim:noet:ft=make:
